-- MySQL Script generated by MySQL Workbench

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema prova2_vendas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `prova2_vendas` ;

-- -----------------------------------------------------
-- Schema prova2_vendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prova2_vendas` DEFAULT CHARACTER SET utf8 ;
USE `prova2_vendas` ;

-- -----------------------------------------------------
-- Table `prova2_vendas`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prova2_vendas`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `quantidade` INT NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prova2_vendas`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prova2_vendas`.`Venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `dataVenda` DATE NOT NULL,
  `qtdeVendida` INT NOT NULL,
  `valorTotal` FLOAT NOT NULL,
  `idProduto` INT NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `fk_Venda_Produto_idx` (`idProduto` ASC),
  CONSTRAINT `fk_Venda_Produto`
    FOREIGN KEY (`idProduto`)
    REFERENCES `prova2_vendas`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
